jupyter_book_task:
  container:
    dockerfile: .ci/Dockerfile
    cpu: 2
    memory: 6G
  build_script: |
    jupyter-book build docs -v
  # pages_script: |
  #   if [[ $CIRRUS_BRANCH == "main" ]]; then
  #     ghp-import -n docs/_build/html
  #     git push -fq https://${GH_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git gh-pages
  #   fi
